[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://pmv-ads-2023-2-e4-proj-dad-t2-votz.onrender.com/api/:splat"
  status = 200

# Roteamento para SPA (Single Page Applications)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200